version: "3.3"

services:
 postgres:
    image: postgres:latest
    container_name: postgr
    restart: always
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=111
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postgres
    networks:
      - database
 lib:
    restart: on-failure
    container_name: cAPIbara
    build: ./
    # entrypoint: dart run /app/bin/conduittest.dart conduit:conduit
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=111
      - DB_HOST=postgr
      - DB_PORT=5432
      - DB_NAME=postgres
      - SECRET_KEY=SECRET_KEY
    depends_on:
      - postgres
    ports:
      - 8888:8888
    networks:
      - database
volumes:
  dart_api:

networks:
  database: